# Generated by Django 6.0.1 on 2026-01-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tecnicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_equipo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_solicitud', models.CharField(max_length=50, unique=True)),
                ('tipo_solicitud', models.CharField(choices=[('INSTALACION', 'Instalación'), ('RETIRO', 'Retiro'), ('PILOTO', 'Piloto')], max_length=20)),
                ('plataforma', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('ON_HOLD', 'On Hold')], default='PENDIENTE', max_length=20)),
                ('status', models.CharField(choices=[('NUEVA', 'Nueva'), ('COORDINANDO_LOGISTICA', 'Coordinando Logística'), ('DESPACHADA', 'Despachada'), ('AGENDADA', 'Agendada'), ('INSTALADA', 'Instalada'), ('NO_INSTALADA', 'No Instalada'), ('RETIRADA', 'Retirada')], default='NUEVA', max_length=30)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='inventario.cliente')),
            ],
            options={
                'db_table': 'solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.solicitud')),
            ],
            options={
                'db_table': 'historial_solicitudes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CoordinacionLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ok_cliente', models.DateField(blank=True, null=True)),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('en_hold', models.BooleanField(default=False)),
                ('fecha_inicio_hold', models.DateField(blank=True, null=True)),
                ('fecha_fin_hold', models.DateField(blank=True, null=True)),
                ('motivo_hold', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistica', to='inventario.solicitud')),
            ],
            options={
                'db_table': 'coordinacion_logistica',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='inventario.cliente')),
            ],
            options={
                'db_table': 'sucursales',
                'ordering': ['cliente', 'nombre'],
                'unique_together': {('cliente', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='inventario.sucursal'),
        ),
        migrations.CreateModel(
            name='CoordinacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(blank=True, null=True)),
                ('horario_visita', models.TimeField(blank=True, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('no_instalada', models.BooleanField(default=False)),
                ('motivo_no_instalacion', models.TextField(blank=True)),
                ('dias_on_hold_validacion', models.IntegerField(default=0)),
                ('dias_on_hold_instalacion', models.IntegerField(default=0)),
                ('comentarios', models.TextField(blank=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnica', to='inventario.solicitud')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='inventario.tecnico')),
            ],
            options={
                'db_table': 'coordinacion_tecnica',
            },
        ),
        migrations.CreateModel(
            name='EquipoInstalado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('RETIRADO', 'Retirado'), ('DEFECTUOSO', 'Defectuoso')], default='OPERATIVO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='inventario.solicitud')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoequipo')),
            ],
            options={
                'db_table': 'equipos_instalados',
                'ordering': ['-fecha_instalacion'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['codigo_solicitud'], name='solicitudes_codigo__1b0624_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', 'status'], name='solicitudes_estado_459274_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['mes', 'anio'], name='solicitudes_mes_603c48_idx'),
        ),
    ]
