# Generated by Django 5.2.8 on 2026-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='datos_red',
            field=models.TextField(blank=True),
        ),
    ]
