# Generated by Django 5.2.8 on 2026-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_solicitud_datos_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinaciontecnica',
            name='fecha_reprogramada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
