# Generated by Django 5.2.8 on 2026-01-20 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_producto_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, help_text='Código de barras para lectura con scanner', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación en bodega/almacén', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada de stock'), ('SALIDA', 'Salida de stock'), ('AJUSTE', 'Ajuste de inventario'), ('DEVOLUCION', 'Devolución'), ('TRANSFERENCIA', 'Transferencia')], default='ENTRADA', max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField(blank=True)),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('referencia_externa', models.CharField(blank=True, help_text='Número de orden de compra, factura, etc.', max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='stock.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['producto', '-fecha'], name='movimientos_product_247093_idx'), models.Index(fields=['tipo', '-fecha'], name='movimientos_tipo_6d0c6f_idx'), models.Index(fields=['usuario', '-fecha'], name='movimientos_usuario_e0827b_idx')],
            },
        ),
    ]
