# Generated by Django 6.0.1 on 2026-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_producto_codigo_barra_producto_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='codigo_escaneado',
            field=models.CharField(blank=True, help_text='Código de barra escaneado exacto', max_length=100),
        ),
    ]
