# Generated by Django 6.0.1 on 2026-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_movimientoinventario_codigo_escaneado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='sku_correlativo',
            field=models.CharField(blank=True, help_text='SKU correlativo generado (CATEGORIA-NNN)', max_length=50),
        ),
    ]
