# Generated by Django 5.2.8 on 2026-01-22 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_movimientoinventario_sku_correlativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMAGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rma', models.CharField(help_text='Número único de RMA (autogenerado)', max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('email_cliente', models.EmailField(blank=True, max_length=254)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('DEVOLUCION', 'Devolución'), ('CAMBIO', 'Cambio'), ('REPARACION', 'Reparación'), ('DEFECTO', 'Defecto de Fábrica'), ('GARANTIA', 'Reclamación por Garantía')], default='DEVOLUCION', max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_compra_original', models.DateField(help_text='Fecha en que se compró el producto original')),
                ('descripcion_problema', models.TextField(help_text='Descripción detallada del problema')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('notas_internas', models.TextField(blank=True)),
                ('producto_devuelto', models.BooleanField(default=False, help_text='Indica si el producto fue devuelto a bodega')),
                ('cantidad_devuelta', models.IntegerField(default=0, help_text='Cantidad de unidades devueltas a bodega')),
                ('cantidad_reemplazo', models.IntegerField(default=0, help_text='Cantidad de productos de reemplazo enviados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('referencia_numero', models.CharField(blank=True, help_text='Número de factura, orden de compra, etc.', max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rmas', to='stock.producto')),
                ('producto_reemplazo', models.ForeignKey(blank=True, help_text='Producto de reemplazo en caso de cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas_como_reemplazo', to='stock.producto')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rma_garantia',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['numero_rma'], name='rma_garanti_numero__a3dbbf_idx'), models.Index(fields=['estado', '-fecha_creacion'], name='rma_garanti_estado_164313_idx'), models.Index(fields=['producto'], name='rma_garanti_product_1ec944_idx')],
            },
        ),
    ]
