# Generated by Django 6.0.1 on 2026-01-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_rmagarantia'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rmagarantia',
            name='rma_garanti_numero__a3dbbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='rmagarantia',
            name='rma_garanti_estado_164313_idx',
        ),
        migrations.RemoveIndex(
            model_name='rmagarantia',
            name='rma_garanti_product_1ec944_idx',
        ),
        migrations.AddField(
            model_name='rmagarantia',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='cantidad_devuelta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='cantidad_reemplazo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='descripcion_problema',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='email_cliente',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='numero_rma',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='producto_reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas_reemplazo', to='stock.producto'),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='referencia_numero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='telefono_cliente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rmagarantia',
            name='tipo',
            field=models.CharField(choices=[('DEVOLUCION', 'Devolución'), ('CAMBIO', 'Cambio'), ('REPARACION', 'Reparación'), ('DEFECTO', 'Defecto de Fábrica'), ('GARANTIA', 'Garantía')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='rmagarantia',
            table=None,
        ),
        migrations.RemoveField(
            model_name='rmagarantia',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='rmagarantia',
            name='fecha_compra_original',
        ),
        migrations.RemoveField(
            model_name='rmagarantia',
            name='producto_devuelto',
        ),
        migrations.RemoveField(
            model_name='rmagarantia',
            name='usuario_creador',
        ),
    ]
