# Generated by Django 6.0.3 on 2026-03-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=200)),
                ('pais', models.CharField(blank=True, db_column='pais', max_length=100, null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
