# Generated by Django 6.0.3 on 2026-03-18 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteNoOperativo',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_no_operativo', serialize=False, to='core.cliente')),
                ('fecha_desactivacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el cliente fue marcado como no operativo')),
                ('motivo_desactivacion', models.CharField(blank=True, help_text='Razón por la cual el cliente fue desactivado', max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el cliente', null=True)),
            ],
            options={
                'verbose_name': 'Cliente No Operativo',
                'verbose_name_plural': 'Clientes No Operativos',
                'ordering': ['-fecha_desactivacion'],
            },
        ),
    ]
